/** v2: stubs for removed Bautizos event-type modules. Auto-extracted from AppMain. */
/** v2: stubs for removed Bautizos event-type modules. Campa baptism: bautizosParty helpers above. */
export const BAUTIZOS_ATTENDANCE = Object.freeze({
  bautizado: 'bautizado', acompanante: 'acompanante', asistente: 'asistente',
  pastor: 'pastor', servidor: 'servidor', cortesia: 'cortesia',
});
export const BAUTIZOS_DASHBOARD_SCOPE_IDS = [];
export const BAUTIZOS_DASHBOARD_SCOPE_OPTIONS = [];
export const BAUTIZOS_UNDER_3_POLICY_NOTE = '';
export const BAUTIZOS_ATTENDANCE_FILTER_OPTIONS = [];
export const BAUTIZOS_TRANSPORT_FILTER_OPTIONS = [];
export const BAUTIZOS_AGE_FILTER_OPTIONS = [];
export const DEFAULT_BAUTIZOS_LIST_PRICE_FOOD = 150;
export const DEFAULT_BAUTIZOS_LIST_PRICE_TRANSPORT = 350;
export const normalizeArrivalCarCount = (v) => Math.max(0, Number(v) || 0);
export const bzEvtNormalizeAttendanceType = (v) => String(v || '').trim();
export const bzEvtNormalizeCompanionsForPersist = (p) => (Array.isArray(p?.bautizosCompanions) ? p.bautizosCompanions : []);
export const bzEvtNormalizeCompanionsForForm = (v) => (Array.isArray(v) ? v : []);
export const bzEvtCompanionsArray = (p) => (Array.isArray(p?.bautizosCompanions) ? p.bautizosCompanions : []);
export const getBautizosLineListPrice = () => 0;
export const bzEvtIsFreeAttendance = () => false;
export const bautizosLineGoesByCar = () => false;
export const bzEvtCompanionBaptized = () => false;
export const bautizosCompanionIsAlsoBautizadoRegistrant = () => false;
export const bzEvtBuildCanonicalCompanionPlan = () => ({ companions: [], byRegistrant: new Map(), meta: {} });
export const buildBautizadoMetaForCanonical = () => ({});
export const buildActiveRegistrantMetaForCompanionDedupe = () => ({});
export const getBautizosBaptizedCompanionSubmitBlockingError = () => null;
export const bzEvtHasBaptizedCompanionInParty = () => false;
export const getBautizosSplitPartySlotDescriptors = () => [];
export const buildParticipantLikeForBautizosSplitSlot = (p) => p;
export const buildSplitPartyCompanionsForSlot = () => [];
export const collectBautizosSplitDerivedCompanionLinkRepairs = () => [];
export const planBautizosSplitPartyMirrorSync = () => ({ repairs: [] });
export const bzEvtSplitPartyHostPerson = () => false;
export const bzEvtSplitPartyGroupMember = () => false;
export const getBautizosSplitPartySubmitBlockingError = () => null;
export const bzEvtLapInfantCompanion = () => false;
export const bzEvtUnder3YearsAtEvent = () => false;
export const bzEvtSyncAttendanceServerFields = (p) => p;
export const bautizosShowsServerParticipation = () => false;
export const bautizosParticipatesAsServer = () => false;
export const bautizosShowsServerProfileFields = () => false;
export const collectBautizosServidoresYEmpleadosRows = () => [];
export const countBautizosServidoresYEmpleadosPeople = () => 0;
export const bautizosCompanionParticipatesAsServer = () => false;
export const countBautizosServersDeduped = () => 0;
export const collectBautizosParticipatingServerRows = () => [];
export const bzEvtAttendanceTypeLabel = () => '';
export const bzEvtAttendanceChipKind = () => null;
export const bzEvtCompanionsVisibleForRegistrant = () => [];
export const buildBautizosExistingCompanionOptions = () => [];
export const bautizosAttendanceUsesParticipantPackage = () => false;
export const bzEvtWillBeBaptizedFromAttendance = () => 'No';
export const bautizosAttendanceDashboardScopeMatches = () => true;
export const bautizosDashboardTitularCountsForScope = () => true;
export const bautizosDashboardCompanionCountsForScope = () => true;
export const bautizosDashboardFilterTitularRows = (rows) => rows;
export const bautizosDashboardFilterCanonicalCompanions = (rows) => rows;
export const countBautizosDashboardPeople = () => 0;
export const bautizosDashboardIncludeRegistrationFinancials = () => true;
export const bautizosDashboardScopeUsesSplitPayments = () => false;
export const participantMatchesBautizosDashboardScope = () => true;
export const resolveBautizosDashboardScopeForSection = () => 'all';
export const resolveBautizosDashboardGlobalScope = () => 'all';
export const normalizeBautizosDashboardScope = () => 'all';
export const getBautizosDashboardScopeChartHint = () => '';
export const getBautizosDashboardScopeLabel = () => '';
export const bzEvtAppendCompanionsValidationIssues = () => {};
export const appendBautizosTransportChoiceIssues = () => {};
export const applyCompanionWaitlistCapOnEdit = ({ nextCompanions }) => nextCompanions || [];
export const buildCompanionWaitlistVirtualParticipant = () => null;
export const clearCompanionWaitlistFlags = (c) => c;
export const collectCompanionWaitlistVirtualRows = () => [];
export const companionDisplayIsWaitlistPending = () => false;
export const computeAdditionalCompanionCapUnits = () => 0;
export const countHostCompanionWaitlistPending = () => 0;
export const isCompanionWaitlistPending = () => false;
export const isCompanionWaitlistVirtualParticipant = () => false;
export const isCompanionWaitlistPhantomStoredParticipant = () => false;
export const parseCompanionWaitlistVirtualId = () => null;
export const resolveCompanionWaitlistSource = () => null;
export const resolveCompanionWaitlistVirtualLocation = (loc) => loc;
export const resolveParticipantEffectiveLocation = (p) => p?.location || '';
export const bzEvtBuildRosterIndex = () => ({
  meta: {}, activeEventRoster: [],
  companionChipCountByRegistrant: new Map(),
  visibleCompanionsByRegistrant: new Map(),
});
export const getCompanionWaitlistVirtualFromIndex = () => [];
export const bzEvtLegacyCompanionVirtualRow = () => false;
export const bzEvtLegacyHostStoredRow = () => false;
export const shouldUseBautizosLegacyPartyFinances = () => false;
export const computeBautizosRosterStatusCountsForLocation = () => ({ active: 0, waitlist: 0, cancelled: 0 });
export const countBautizosWaitlistExpandedPeople = () => 0;
export const bautizosPartyCancelModalApplies = () => false;
export const getBautizosPartyCancelTargetMeta = () => null;
export const listBautizosPartyCancelTargets = () => [];
export const planBautizosPartyCancelArchive = () => ({ archives: [] });
export const prepareBautizosRowsForRosterFilter = (rows) => rows;
export const applyTitularOnlyBautizosRosterFilters = (rows) => rows;
export const participantMatchesBautizosTransportFilter = () => true;
export const bzEvtBuildFamilyCarInventory = () => ({ cars: [] });
export const buildCarDataSummaryForRosterPerson = () => null;
export const buildCarDataWaSubjectContext = () => ({});
export const buildCarMetaPatchesAfterSave = () => [];
export const buildMergedFamilyCarInventory = () => ({ cars: [] });
export const carCrewRequiresPassengerSelection = () => false;
export const collectCarColorSuggestions = () => [];
export const familyCarInventoryNeedsAttention = () => false;
export const familyHasAnyCarTransport = () => false;
export const getFamilyCarInventoryValidationIssues = () => [];
export const bzEvtResolveCarDataAnchor = () => null;
export const resolveLinkedCompanionCarInheritance = () => null;
export const getBautizosSplitPartyHostListPrice = () => 0;
export const getBautizosListPriceBreakdown = () => ({ food: 0, transport: 0, total: 0 });
export const getBautizosTitularListPrice = () => 0;
export const bzEvtCompanionsInformativeListPriceSum = () => 0;
export const getBautizosCompanionInformativeListPrice = () => 0;
export const allocateBautizosDashboardPayments = () => null;
export const buildBautizosDashboardLiquidationUnits = () => [];
export const countBautizosFifoLiquidationUnits = () => ({ paidOff: 0, withDebt: 0 });
export const getBautizosPartyLiquidationSplit = () => ({ titularOwed: 0 });
export const getBautizosGlobalRegistryRowOutstandingGross = () => 0;
export const resolveBautizosGlobalRegistryRowFinances = () => null;
export const describeNewRegistrationCompanions = () => '';
export const buildPromoteCompanionWaitlistWhatsAppMessage = () => '';
export const uiBautizosAttendanceChip = '';
export const BzEvtAttendanceTypeField = () => null;
export const BzEvtCompanionsField = () => null;
export const BautizosServerParticipationFields = () => null;
export const BzEvtCarDataSection = () => null;
export const BzEvtCarDataPromptModal = () => null;
export const BzEvtCarDataSummaryCard = () => null;
export const BzEvtAttendanceTypeChip = () => null;
