export const defaultViewPrefs = {
  statsConfig: true,
  chartLocations: true,
  chartBautizosCompanionSplit: true,
  chartBautizosTransportCar: true,
  chartIncome: true,
  chartPaymentStatus: true,
  chartGender: true,
  chartAgeBrackets: true,
  chartBloodType: true,
  chartScholarship: true,
  chartSwimming: true,
  chartMedical: true,
  chartServers: true,
  chartAges: true,
  chartBaptism: true,
  chartAttendanceSpecial: true,
  chartCustom: true,
  tableDetails: true,
};

export const SUMMARY_TABLE_COLUMN_DEFAULTS = {
  count: true,
  scholarship: true,
  serveYes: true,
  serveNo: true,
  bautizos: true,
  teens: true,
  jovenes: true,
  cortesia: false,
  pastores: true,
  waitlist: true,
  cancelled: true,
  refund: true,
  donations: true,
  paid: true,
  paidEfectivo: true,
  paidTarjeta: true,
  pending: true,
  expected: false,
};

/** Visibilidad por defecto en «Visualización de Datos Generales» para eventos Bautizos. */
export const SUMMARY_TABLE_COLUMN_DEFAULTS_BAUTIZOS = {
  count: true,
  bautizados: true,
  companions: true,
  asistentesBautizos: true,
  bautizosTransport: true,
  bautizosCarro: true,
  serveYes: true,
  cortesia: true,
  empleadosBautizos: true,
  pastores: true,
  waitlist: true,
  cancelled: true,
  refund: true,
  paid: true,
  donations: true,
  paidEfectivo: true,
  paidTarjeta: true,
  pending: true,
  expected: false,
  scholarship: false,
  serveNo: false,
  bautizos: false,
  teens: false,
  jovenes: false,
};

export const SUMMARY_TABLE_COLUMN_LABELS = {
  count: 'Inscritos',
  bautizados: 'Bautizados',
  companions: 'Acompañantes',
  asistentesBautizos: 'Asistentes',
  bautizosTransport: 'Transp. evento',
  bautizosCarro: 'Llevan carro',
  empleadosBautizos: 'Empleados',
  pastores: 'Pastores',
  scholarship: 'Becados',
  serveYes: 'Servidores',
  serveNo: 'Camperos',
  bautizos: 'Bautizos',
  teens: 'Teens',
  jovenes: 'Jóvenes',
  waitlist: 'Lista de espera',
  cancelled: 'Cancelados',
  refund: 'Con devolución',
  paid: 'Recaudado',
  donations: 'Donaciones',
  paidEfectivo: 'Efectivo',
  paidTarjeta: 'Tarjeta',
  pending: 'Pendiente',
  cortesia: 'Cortesías',
  expected: 'Total esperado',
};

/** Orden de columnas en «Visualización de Datos Generales» (1 + columnas visibles). */
export const SUMMARY_TABLE_COLUMN_KEYS = [
  'count',
  'scholarship',
  'serveYes',
  'serveNo',
  'bautizos',
  'teens',
  'jovenes',
  'waitlist',
  'cancelled',
  'refund',
  'paid',
  'donations',
  'paidEfectivo',
  'paidTarjeta',
  'pending',
  'cortesia',
  'pastores',
  'expected',
];

/** Columnas y orden para eventos tipo Bautizos (sin Camperos/Becados/Teens/Jóvenes en tabla). */
export const SUMMARY_TABLE_COLUMN_KEYS_BAUTIZOS = [
  'count',
  'bautizados',
  'companions',
  'asistentesBautizos',
  'bautizosTransport',
  'bautizosCarro',
  'serveYes',
  'empleadosBautizos',
  'pastores',
  'cortesia',
  'waitlist',
  'cancelled',
  'refund',
  'paid',
  'donations',
  'paidEfectivo',
  'paidTarjeta',
  'pending',
  'expected',
];

export const getSummaryTableColumnKeysForEventType = (eventType) =>
  eventType === 'Bautizos' ? SUMMARY_TABLE_COLUMN_KEYS_BAUTIZOS : SUMMARY_TABLE_COLUMN_KEYS;

export const getSummaryTableColumnDefaultsForEventType = (eventType) =>
  eventType === 'Bautizos' ? SUMMARY_TABLE_COLUMN_DEFAULTS_BAUTIZOS : SUMMARY_TABLE_COLUMN_DEFAULTS;

export const SUMMARY_TABLE_MONEY_KEYS = new Set([
  'paid',
  'donations',
  'paidEfectivo',
  'paidTarjeta',
  'pending',
  'expected',
]);
