import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const p = path.join(__dirname, '..', 'src', 'screens', 'EventWorkspaceScreen.jsx');

/** Solo identificadores de ámbito App; no incluir nombres cortos de locales (exp, loc, m, remaining, …). */
const WORDS = [
  'MASKED_EXPENSE_CONCEPT_LABEL',
  'activeTab',
  'addLog',
  'allParticipants',
  'allergyOptionsForm',
  'allergyOptionsModal',
  'btnPrimary',
  'btnSecondary',
  'canAccessExpenses',
  'canSeeExpenseConceptForRow',
  'cashCutScheduleModal',
  'closePaymentMethodEditModal',
  'closeSuperDateEditModal',
  'cola',
  'currentEvent',
  'currentUser',
  'customFieldsModal',
  'data',
  'debugToast',
  'donationModal',
  'donations',
  'donationsListOpen',
  'editRegistryModal',
  'editorRegFieldsModalEl',
  'expenseEditModal',
  'expensePartialModal',
  'expenses',
  'fbUser',
  'formatMoney',
  'formatPhoneNumber',
  'getAutoPaymentService',
  'getDocRef',
  'globalConfig',
  'goBack',
  'goTo',
  'handleAddCustomField',
  'handleAddDonation',
  'handleAddLocation',
  'handleDeleteLocation',
  'handleEditExpense',
  'handleExpensePartialPayment',
  'handleExportExcel',
  'handleLogout',
  'handleRemoveCustomField',
  'handleSaveAllergyOptions',
  'handleSaveCashCutScheduleByLocation',
  'handleSavePaymentMethodEdit',
  'handleSavePricing',
  'handleSaveServeAreaOptions',
  'handleSuperSaveDateEdit',
  'handleUpdateEntry',
  'hasAdminRights',
  'hasFinancialAccess',
  'inputClasses',
  'inputClassesPhase',
  'isAddLocModalOpen',
  'isCampa',
  'isExporting',
  'isLocOpen',
  'isMobileMenuOpen',
  'isPanelNavSectionAllowed',
  'isSuperUser',
  'labelClasses',
  'labelClassesPhase',
  'locError',
  'mergeEventDonationsForEvent',
  'navHistory',
  'newCustomField',
  'newLocationName',
  'omitUndefinedDeep',
  'openDeleteDonationConfirm',
  'panelNavModalEl',
  'paymentMethodEditModal',
  'paymentModal',
  'pricingForm',
  'pricingModal',
  'publicQrBusy',
  'publicQrDataUrl',
  'publicQrModalOpen',
  'publicQrUrl',
  'renderBecadosPage',
  'renderCashCutPage',
  'renderEditRegistryModalFormFields',
  'renderExpenseListPage',
  'renderGlobalRegistryPage',
  'renderLocationSheet',
  'renderRegistryConfirmModal',
  'renderServerProfilesPage',
  'renderSummary',
  'resetEditRegistryModal',
  'selectedEventId',
  'sendWhatsAppMessage',
  'serveAreaOptionsForm',
  'serveAreaOptionsModal',
  'setAllergyOptionsForm',
  'setAllergyOptionsModal',
  'setCashCutScheduleModal',
  'setCashCutSlotTimeForLoc',
  'setCustomFieldsModal',
  'setDoc',
  'setDonationModal',
  'setDonationsListOpen',
  'setExpenseEditModal',
  'setExpensePartialModal',
  'setIsAddLocModalOpen',
  'setIsMobileMenuOpen',
  'setNewCustomField',
  'setNewLocationName',
  'setPaymentMethodEditModal',
  'setPaymentModal',
  'setPricingForm',
  'setPricingModal',
  'setPublicQrBusy',
  'setPublicQrDataUrl',
  'setPublicQrModalOpen',
  'setPublicQrOptional',
  'setPublicQrUrl',
  'setRenameModal',
  'setServeAreaOptionsForm',
  'setServeAreaOptionsModal',
  'setShowMoney',
  'setSuperDateEditModal',
  'setTempEventDate',
  'setWhatsAppModal',
  'showMoney',
  'showToast',
  'submitAbono',
  'summary',
  'superDateEditModal',
  'superSessionCount',
  'syncFirestoreBusy',
  'syncFirestoreFromServer',
  'systemView',
  'tempEventDate',
  'toggleCashCutServiceForLoc',
  'toggleDebugMode',
  'toast',
  'updateDoc',
  'visibleLocations',
  'whatsAppModal',
];

const full = fs.readFileSync(p, 'utf8');
const marker = 'export default function EventWorkspaceScreen';
const idx = full.indexOf(marker);
const head = idx === -1 ? '' : full.slice(0, idx);
let code = idx === -1 ? full : full.slice(idx);
const sorted = [...WORDS].sort((a, b) => b.length - a.length);
for (const w of sorted) {
  const re = new RegExp(`(?<!shell\\.)\\b${w}\\b`, 'g');
  code = code.replace(re, `shell.${w}`);
}
code = code.replace(/shell\.shell\./g, 'shell.');
fs.writeFileSync(p, head + code, 'utf8');
console.log('fixed', p);
