# -*- coding: utf-8 -*-
"""Replace mojibake patterns (? for lost UTF-8) in App.jsx user-facing and string literals."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
TARGET = ROOT / "src" / "App.jsx"

# Longest keys first — order matters
REPLACEMENTS = [
    # Métricas Excel / encabezados (mayúsculas)
    ("M?TRICAS: ASIGNACI?N / SERVIDORES", "MÉTRICAS: ASIGNACIÓN / SERVIDORES"),
    ("M?TRICAS: CAMPOS PERSONALIZADOS", "MÉTRICAS: CAMPOS PERSONALIZADOS"),
    ("M?TRICAS: BAUTIZOS (conteo por segmento del evento)", "MÉTRICAS: BAUTIZOS (conteo por segmento del evento)"),
    ("M?TRICAS: RANGOS DE EDAD", "MÉTRICAS: RANGOS DE EDAD"),
    ("M?TRICAS: G?NERO", "MÉTRICAS: GÉNERO"),
    ("M?TRICAS PRINCIPALES", "MÉTRICAS PRINCIPALES"),
    ("M?TRICAS: SALUD", "MÉTRICAS: SALUD"),
    ("M?TRICAS: NADO", "MÉTRICAS: NADO"),
    ("M?TRICAS", "MÉTRICAS"),
    ("G?NERO", "GÉNERO"),
    ("ATENCI?N SUPERUSUARIO:", "ATENCIÓN SUPERUSUARIO:"),
    ("DEPURACI?N", "DEPURACIÓN"),
    ("?Nos vemos el", "¡Nos vemos el"),
    ("Iniciando sesión?", "Iniciando sesión…"),
    ("Selecciona?", "Seleccionar"),
    ("Ordenar?", "Ordenar…"),
    ("VNPM?", "VNPM…"),
    ("BOT?N EXPORTAR", "BOTÓN EXPORTAR"),
    ("?Sabe nadar?:", "¿Sabe nadar?:"),
    ("?Sabe nadar?", "¿Sabe nadar?"),
    ("?Es casado?", "¿Es casado?"),
    ("?Va con hijos?", "¿Va con hijos?"),
    ("?Han servido en otro campa?", "¿Han servido en otro campa?"),
    ("?Sirven en sus congres?", "¿Sirven en sus congresos?"),
    ("Sirvi? en otro campa", "Sirvió en otro campa"),
    ("Registr? un abono", "Registró un abono"),
    ("Registr?", "Registró"),
    ("Columna ?Participante?", "Columna «Participante»"),
    ("Firestore rechaz? la lectura", "Firestore rechazó la lectura"),
    ("Llega cami?n / Regresa cami?n", "Llega camión / Regresa camión"),
    ("Llega carro / Regresa cami?n", "Llega carro / Regresa camión"),
    ("Llega cami?n / Regresa carro", "Llega camión / Regresa carro"),
    ("Inicio de Sesi?n", "Inicio de Sesión"),
    ("Ya hay una sesi?n activa", "Ya hay una sesión activa"),
    ("autom?ticamente", "automáticamente"),
    ("autom?tico", "automático"),
    ("antig?edad", "antigüedad"),
    ("ambig?edad", "ambigüedad"),
    ("espec?fica", "específica"),
    ("espec?fico", "específico"),
    ("m?ltiples", "múltiples"),
    ("Promoci?n", "Promoción"),
    ("promoci?n", "promoción"),
    ("transacci?n", "transacción"),
    ("Transacci?n", "Transacción"),
    ("informaci?n", "información"),
    ("Informaci?n", "Información"),
    ("configuraci?n", "configuración"),
    ("Configuraci?n", "Configuración"),
    ("aplicaci?n", "aplicación"),
    ("Aplicaci?n", "Aplicación"),
    ("eliminaci?n", "eliminación"),
    ("Eliminaci?n", "Eliminación"),
    ("confirmaci?n", "confirmación"),
    ("Confirmaci?n", "Confirmación"),
    ("exportaci?n", "exportación"),
    ("depuraci?n", "depuración"),
    ("Depuraci?n", "Depuración"),
    ("asignaci?n", "asignación"),
    ("Asignaci?n", "Asignación"),
    ("ubicaci?n", "ubicación"),
    ("Ubicaci?n", "Ubicación"),
    ("devoluci?n", "devolución"),
    ("auditor?a", "auditoría"),
    ("Auditor?a", "Auditoría"),
    ("versi?n", "versión"),
    ("Versi?n", "Versión"),
    ("mediod?a", "mediodía"),
    ("contrase?a", "contraseña"),
    ("Contrase?a", "Contraseña"),
    ("tel?fono", "teléfono"),
    ("Tel?fono", "Teléfono"),
    ("tel?fonos", "teléfonos"),
    ("n?mero", "número"),
    ("N?mero", "Número"),
    ("n?meros", "números"),
    ("d?gitos", "dígitos"),
    ("m?todo", "método"),
    ("M?todo", "Método"),
    ("m?todos", "métodos"),
    ("M?todos", "Métodos"),
    ("campa?a", "campaña"),
    ("Campa?a", "Campaña"),
    ("campa?as", "campañas"),
    ("Campa?as", "Campañas"),
    ("edici?n", "edición"),
    ("Edici?n", "Edición"),
    ("pesta?a", "pestaña"),
    ("Pesta?a", "Pestaña"),
    ("pesta?as", "pestañas"),
    ("sesi?n", "sesión"),
    ("Sesi?n", "Sesión"),
    ("J?venes", "Jóvenes"),
    ("j?venes", "jóvenes"),
    ("Cami?n", "Camión"),
    ("cami?n", "camión"),
    ("cortes?a", "cortesía"),
    ("Cortes?a", "Cortesía"),
    ("hist?ricas", "históricas"),
    ("hist?rico", "histórico"),
    ("sem?ntica", "semántica"),
    ("l?gica", "lógica"),
    ("l?gicos", "lógicos"),
    ("l?nea", "línea"),
    ("l?neas", "líneas"),
    ("G?nero", "Género"),
    ("g?nero", "género"),
    ("Ni?os", "Niños"),
    ("ni?o", "niño"),
    ("Gr?ficas", "Gráficas"),
    ("gr?ficas", "gráficas"),
    ("vac?as", "vacías"),
    ("inv?lida", "inválida"),
    ("v?lidas", "válidas"),
    ("v?lido", "válido"),
    ("v?lida", "válida"),
    ("conexi?n", "conexión"),
    ("Conexi?n", "Conexión"),
    ("librer?a", "librería"),
    ("as?ncrona", "asíncrona"),
    ("as?ncrono", "asíncrono"),
    ("gen?rico", "genérico"),
    ("?ndice", "Índice"),
    ("?nico", "único"),
    ("?nica", "única"),
    ("?ltimo", "Último"),
    ("?ltima", "Última"),
    ("B?squeda", "Búsqueda"),
    ("b?squeda", "búsqueda"),
    ("P?gina", "Página"),
    ("p?gina", "página"),
    ("Secci?n", "Sección"),
    ("secci?n", "sección"),
    ("comisi?n", "comisión"),
    ("Adem?s", "Además"),
    ("adem?s", "además"),
    ("tambi?n", "también"),
    ("Tambi?n", "También"),
    ("aqu?", "aquí"),
    ("Aqu?", "Aquí"),
    ("m?s", "más"),
    ("M?s", "Más"),
    ("s?lo", "sólo"),
    ("S?lo", "Sólo"),
    ("d?as", "días"),
    ("D?as", "Días"),
    ("seg?n", "según"),
    ("cu?l", "cuál"),
    ("Cu?l", "Cuál"),
    ("?Deseas", "¿Deseas"),
    ("?Est?s", "¿Estás"),
    ("?Eliminar", "¿Eliminar"),
    ("?Confirmas", "¿Confirmas"),
    ("?Archivar", "¿Archivar"),
    ("?Cu?l", "¿Cuál"),
    ("?cu?l", "¿cuál"),
    ("recuper? ", "recuperó "),
    ("activ? ", "activó "),
    ("activ?.", "activó."),
    ("termin?.", "terminó."),
    ("Sali? de", "Salió de"),
    ("Actualiz? ", "Actualizó "),
    ("registr?", "registró"),
    ("sobrescribir?", "sobrescribirá"),
    ("eliminar?n", "eliminarán"),
    ("ser?n ", "serán "),
    ("est?n ", "están "),
    ("est?s ", "estás "),
    ("est? ", "está "),
    ("est?.", "está."),
    ("est?,", "está,"),
    ("est? ", "está "),  # duplicate safe
    ("no est?", "no está"),
    ("Firestore est?", "Firestore está"),
    ("qu? secciones", "qué secciones"),
    ("qu? ven", "qué ven"),
    ("Men? lateral", "Menú lateral"),
    ("men? lateral", "menú lateral"),
    ("el men?", "el menú"),
    ("del men?", "del menú"),
    ("al men?", "al menú"),
    ("Men? ", "Menú "),
    (" men?", " menú"),
    ("Din?mico", "Dinámico"),
    ("din?mico", "dinámico"),
    ("din?mica", "dinámica"),
    ("A?adir", "Añadir"),
    ("a?adir", "añadir"),
    ("Ubicaci?n", "Ubicación"),
    ("ubicaci?n", "ubicación"),
    ("Categor?as", "Categorías"),
    ("categor?a", "categoría"),
    ("opci?n", "opción"),
    ("Opci?n", "Opción"),
    ("opci?nes", "opciones"),
    ("?rea", "área"),
    ("?reas", "áreas"),
    ("?En qu?", "¿En qué"),
    ("gustar?a", "gustaría"),
    ("cami?n", "camión"),
    ("??ltimo", "Último"),
    ("?ltimo", "Último"),
    ("?nico", "único"),
    ("?nica", "única"),
    ("?ltima", "Última"),
    ("???", "…"),
    ("s? cuentan", "sí cuentan"),
    (" expl?ci", " explící"),
    ("expl?citamente", "explícitamente"),
    (" vi?ndola", " viéndola"),
    (" ten?an", " tenían"),
    (" administraci?n", " administración"),
    ("Iniciar sesi?n", "Iniciar sesión"),
    ("sesi?n.", "sesión."),
    ("Sistema de Gesti?n", "Sistema de Gestión"),
    ("Gesti?n de", "Gestión de"),
    ("gesti?n", "gestión"),
    ("Gesti?n", "Gestión"),
    ("Documentaci?n", "Documentación"),
    ("Valor can?nico", "Valor canónico"),
    ("codificaci?n", "codificación"),
    ("Visualizaci?n", "Visualización"),
    (" visualizaci?n", " visualización"),
    (" precisi?n", " precisión"),
    (" decisi?n", " decisión"),
    ("Versi?n del", "Versión del"),
    ("ATENCI??N", "ATENCIÓN"),
    ("irreversible", "irreversible"),
    ("SuperUsuario", "SuperUsuario"),
    ("?Salir?", "«Salir»"),
    (" o dispositivo", " o dispositivo"),
    ("perfil en la aplicaci?n", "perfil en la aplicación"),
    ("aplicaci?n.", "aplicación."),
    ("Aplicaci?n", "Aplicación"),
    ("l?gica:", "lógica:"),
    (" num?rico", " numérico"),
    ("Semana inv?lida", "Semana inválida"),
    ("?rea deseada", "área deseada"),
    ("?reas previas", "áreas previas"),
    ("?rea en congreso", "área en congreso"),
    ("?ltimo movimiento", "Último movimiento"),
    ("m?s reciente", "más reciente"),
    ("Campa?a aplicada", "Campaña aplicada"),
    ("Campa?a quitada", "Campaña quitada"),
    ("campa?a;", "campaña;"),
    ("Campa?a", "Campaña"),
    ("campa?a", "campaña"),
    ("Categor?a", "Categoría"),
    ("Donaci?n", "Donación"),
    ("donaci?n", "donación"),
    ("Registrando", "Registrando"),
    ("Registrar Donaci?n", "Registrar Donación"),
    ("Nueva Donaci?n", "Nueva Donación"),
    ("Eliminar donaci?n", "Eliminar donación"),
    ("la donaci?n", "la donación"),
    ("Sede", "Sede"),
    ("A?adir Sede", "Añadir Sede"),
    ("A?adir Nueva Sede", "Añadir Nueva Sede"),
    ("A?adir Nuevo Campo", "Añadir Nuevo Campo"),
    ("ubicaci?n para", "ubicación para"),
    ("Quer?taro", "Querétaro"),
    ("Ej. Quer?taro", "Ej. Querétaro"),
    ("Cambio de Contrase?a", "Cambio de Contraseña"),
    ("Contrase?a Actual", "Contraseña Actual"),
    ("Nueva Contrase?a", "Nueva Contraseña"),
    ("Confirmar Nueva Contrase?a", "Confirmar Nueva Contraseña"),
    ("Cambiar contrase?a", "Cambiar contraseña"),
    ("Ocultar contrase?a", "Ocultar contraseña"),
    ("Mostrar contrase?a", "Mostrar contraseña"),
    ("Configuraci?n de Precios", "Configuración de Precios"),
    ("Elige si el precio ser?", "Elige si el precio será"),
    ("cambiar? autom", "cambiará autom"),
    ("seg?n la fecha", "según la fecha"),
    ("A?adir Fase", "Añadir Fase"),
    ("A?adir campa?a", "Añadir campaña"),
    ("+ A?adir campa?a", "+ Añadir campaña"),
    ("folio / transacci?n", "folio / transacción"),
    ("??ltimo movimiento financiero", "Último movimiento financiero"),
    ("gen?rico de saldo", "genérico de saldo"),
    ("promoci?n desde", "promoción desde"),
    ("promoci?n,", "promoción,"),
    ("est? habilitada", "está habilitada"),
    ("no est? habilitada", "no está habilitada"),
    ("T?tulo del Evento", "Título del Evento"),
    ("Campamento J?venes", "Campamento Jóvenes"),
    ("Renombrar Evento", "Renombrar Evento"),
    ("Ingresa el nuevo nombre", "Ingresa el nuevo nombre"),
    ("Nombre del Evento", "Nombre del Evento"),
    ("Fecha del Evento", "Fecha del Evento"),
    ("Tipo de Evento", "Tipo de Evento"),
    ("Nuevo Evento", "Nuevo Evento"),
    ("Eliminar Evento", "Eliminar Evento"),
    ("archivar?n", "archivarán"),
    ("acci?n no se puede", "acción no se puede"),
    ("Esta acci?n", "Esta acción"),
    ("esta acci?n", "esta acción"),
    ("acci?n espec", "acción espec"),
    ("acci?n revert", "acción revert"),
    ("m?s de 30", "más de 30"),
    ("menos de 30 d?as", "menos de 30 días"),
    ("d?gitos", "dígitos"),
    ("g?nero", "género"),
    ("completa nombre", "completa nombre"),
    ("Campa?a no v", "Campaña no v"),
    ("v?lida o desactivada", "válida o desactivada"),
    ("Esa campa?a", "Esa campaña"),
    ("campa?a no aplica", "campaña no aplica"),
    ("campa?a;", "campaña;"),
    ("sin fechas en campa?a", "sin fechas en campaña"),
    ("fuera de vigencia por fechas; aplicaci?n manual", "fuera de vigencia por fechas; aplicación manual"),
    ("Campa?a aplicada", "Campaña aplicada"),
    ("Campa?a quitada", "Campaña quitada"),
    ("campa?a elegida", "campaña elegida"),
    ("sin vigencia por fecha", "sin vigencia por fecha"),
    ("editar un registro", "editar un registro"),
    ("Solo administrador puede aplicar o quitar campa?as", "Solo administrador puede aplicar o quitar campañas"),
    ("Puedes editarlo despu?s", "Puedes editarlo después"),
    ("despu?s a mano", "después a mano"),
    ("Si ya pag? de m?s", "Si ya pagó de más"),
    ("tras bajar el costo", "tras bajar el costo"),
    ("puede quedar devoluci?n", "puede quedar devolución"),
    ("Dejar? de contar", "Dejará de contar"),
    ("Dejar? de restarse", "Dejará de restarse"),
    ("obligaci?n ya no", "obligación ya no"),
    ("Categor?as de alergias", "Categorías de alergias"),
    ("Agregar categor?a", "Agregar categoría"),
    ("Agregar opci?n", "Agregar opción"),
    ("Nombre de categor?a", "Nombre de categoría"),
    ("Nombre de opci?n", "Nombre de opción"),
    ("Horarios de Servicio", "Horarios de Servicio"),
    ("Juan P?rez", "Juan Pérez"),
    ("Escribe el mensaje", "Escribe el mensaje"),
    ("Tel?fono (WhatsApp)", "Teléfono (WhatsApp)"),
    ("Mensaje para", "Mensaje para"),
    ("Sin avisos en cola", "Sin avisos en cola"),
    ("m?s reciente", "más reciente"),
    ("Cargando???", "Cargando…"),
    ("???", "…"),
    # --- Round 2: restos tras primera pasada (no ejecutar dos veces seguidas sobre UTF-8 ya bueno) ---
    ("l\uFFFDmite", "límite"),
    ("?activa?", "«activa»"),
    ("M??TRICAS: ASIGNACI??N / SERVIDORES", "MÉTRICAS: ASIGNACIÓN / SERVIDORES"),
    ("M??TRICAS: CAMPOS PERSONALIZADOS", "MÉTRICAS: CAMPOS PERSONALIZADOS"),
    ("M??TRICAS: BAUTIZOS (conteo por segmento del evento)", "MÉTRICAS: BAUTIZOS (conteo por segmento del evento)"),
    ("M??TRICAS: SALUD", "MÉTRICAS: SALUD"),
    ("M??TRICAS: NADO", "MÉTRICAS: NADO"),
    ("M??TRICAS: RANGOS DE EDAD", "MÉTRICAS: RANGOS DE EDAD"),
    ("M??TRICAS: G??NERO", "MÉTRICAS: GÉNERO"),
    ("M??TRICAS PRINCIPALES", "MÉTRICAS PRINCIPALES"),
    ("G??NERO", "GÉNERO"),
    ("M??TRICAS", "MÉTRICAS"),
    ("ASIGNACI??N", "ASIGNACIÓN"),
    ("mostrar?n como ?Oculto? a otros (t? y SuperUsuario ver?n", "mostrarán como «Oculto» a otros (tú y SuperUsuario verán"),
    ("Últimas dos palabras ?tiles", "Últimas dos palabras útiles"),
    ("para excepci?n de teléfono", "para excepción de teléfono"),
    ("apartado m?nimo del evento", "apartado mínimo del evento"),
    ("mediodía local para que el d?a civil", "mediodía local para que el día civil"),
    ("medianoche ? d?a anterior", "medianoche … día anterior"),
    ("Exportaci?n de Datos", "Exportación de Datos"),
    ("Descarg? la base", "Descargó la base"),
    ("con ?xito", "con éxito"),
    ("?xito.", "éxito."),
    ("copia autom?tica no se eliminan (restauraci?n disponible)", "copia automática no se eliminan (restauración disponible)"),
    ("copia autom?tica se conservan", "copia automática se conservan"),
    ("Restauraci?n Masiva", "Restauración Masiva"),
    ("Restauraci?n de Sistema", "Restauración de Sistema"),
    ("addLog('Restauraci?n',", "addLog('Restauración',"),
    ("revirti? todos", "revirtió todos"),
    ("restaur? el sistema", "restauró el sistema"),
    ("Error cr?tico al restaurar", "Error crítico al restaurar"),
    ("escr?belo completo", "escríbelo completo"),
    ("Copia de seguridad autom?tica diaria", "Copia de seguridad automática diaria"),
    ("'Cierre de Sesión Autom?tico'", "'Cierre de Sesión Automático'"),
    ("addLog('Cierre de Sesión Autom?tico'", "addLog('Cierre de Sesión Automático'"),
    ("desde cach? atr?s", "desde caché atrás"),
    ("`Atenci?n:", "`Atención:"),
    ("Todas las fases deben tener una fecha l?mite", "Todas las fases deben tener una fecha límite"),
    ("fecha l?mite del evento", "fecha límite del evento"),
    ("la misma fecha l?mite", "la misma fecha límite"),
    ("registro de nuevo ?tem", "registro de nuevo ítem"),
    ("eliminación de ?tem", "eliminación de ítem"),
    ("edición de ?tem", "edición de ítem"),
    ("cambio de contabilizaci?n en totales", "cambio de contabilización en totales"),
    ("`A?adi? al nuevo usuario", "`Añadió al nuevo usuario"),
    ("Usuario a?adido exitosamente", "Usuario añadido exitosamente"),
    ("no puede estar vac?a", "no puede estar vacía"),
    ("en la n?mina activa", "en la nómina activa"),
    ("aprobaci?n administrativa", "aprobación administrativa"),
    ("hasta el pr?ximo abono", "hasta el próximo abono"),
    ("`A?adi? la nueva sede", "`Añadió la nueva sede"),
    ("Sede a?adida", "Sede añadida"),
    ("`Elimin? la sede vac?a", "`Eliminó la sede vacía"),
    ("`A?adi? el campo", "`Añadió el campo"),
    ("Registro a?adido exitosamente", "Registro añadido exitosamente"),
    ("aprobaci?n al promover", "aprobación al promover"),
    ("`A?adi? a ${newEntry.name}", "`Añadió a ${newEntry.name}"),
    ("addLog('Actualizaci?n de Registro'", "addLog('Actualización de Registro'"),
    ("`Modific? datos de", "`Modificó datos de"),
    ("clicks r?pidos", "clicks rápidos"),
    ("completar la acci?n", "completar la acción"),
    ("'Reactivaci?n de Registro'", "'Reactivación de Registro'"),
    ("M?ximo a abonar", "Máximo a abonar"),
    ("no exist?a registeredAt", "no existía registeredAt"),
    ("copia autom?tica.", "copia automática."),
    ("(restauraci?n disponible)", "(restauración disponible)"),
    ("<option value=\"day\">Fecha: D?a</option>", "<option value=\"day\">Fecha: Día</option>"),
    ("action: 'Copia de seguridad autom?tica'", "action: 'Copia de seguridad automática'"),
    ("?Última copia autom?tica", "Última copia automática"),
    ("<th className=\"px-6 py-4 text-center\">Acci?n</th>", "<th className=\"px-6 py-4 text-center\">Acción</th>"),
    ("la organizaci?n deja", "la organización deja"),
    ("Comisi?n tarjeta", "Comisión tarjeta"),
    ("<th className=\"px-4 py-2.5 text-right\">Comisi?n</th>", "<th className=\"px-4 py-2.5 text-right\">Comisión</th>"),
    ("Contabilizaci?n</p>", "Contabilización</p>"),
    ("El SuperUsuario puede eliminar un rengl?n", "El SuperUsuario puede eliminar un renglón"),
    ("Recaudaci?n … Costo", "Recaudación … Costo"),
    ("{ key: 'chartLocations', label: 'Gr?fica: Sedes' }", "{ key: 'chartLocations', label: 'Gráfica: Sedes' }"),
    ("label: 'Gr?fica:", "label: 'Gráfica:"),
    ("Apartado M?n.", "Apartado Mín."),
    ("Apartado m?n:", "Apartado mín:"),
    ("…Registrar… env?a automáticamente", "…Registrar… envía automáticamente"),
    ("Proporci?n de inscritos", "Proporción de inscritos"),
    ("Porcentaje de recaudaci?n", "Porcentaje de recaudación"),
    ("Distribuci?n detallada por edades", "Distribución detallada por edades"),
    ("Distribuci?n de participantes por tipo de sangre", "Distribución de participantes por tipo de sangre"),
    ("a?n.", "aún."),
    ("a?n</p>", "aún</p>"),
    ("Habilidades Acu?ticas", "Habilidades Acuáticas"),
    ("condiciones m?dicas especiales", "condiciones médicas especiales"),
    ("Distribuci?n de servidores por asignación", "Distribución de servidores por asignación"),
    ("define d?nde cuenta", "define dónde cuenta"),
    ("Distribuci?n de respuestas", "Distribución de respuestas"),
    ("Distribuci?n en valores absolutos", "Distribución en valores absolutos"),
    ("Devoluci?n pendiente", "Devolución pendiente"),
    ("Vac?a todos los campos", "Vacía todos los campos"),
    ("Pérez L?pez", "Pérez López"),
    ("{/* 3. Datos m?dicos (Campa) */}", "{/* 3. Datos médicos (Campa) */}"),
    ("3 ? Datos m?dicos", "3 · Datos médicos"),
    ("?D?nde se bautiza?", "¿Dónde se bautiza?"),
    ("?Cu?ntos?", "¿Cuántos?"),
    ("Parcial: $0, m?n.", "Parcial: $0, mín."),
    ("M?n. ${", "Mín. ${"),
    ("<option value=\"\">Autom?tico (fechas vigentes hoy)</option>", "<option value=\"\">Automático (fechas vigentes hoy)</option>"),
    ("Acciones r?pidas", "Acciones rápidas"),
    ("Ning?n cancelado", "Ningún cancelado"),
    ("Overlay del Menú M?vil", "Overlay del Menú Móvil"),
    ("Bot?n Hamburguesa para M?viles", "Botón Hamburguesa para Móviles"),
    ("Se generar? al guardar si a?n no existe", "Se generará al guardar si aún no existe"),
    ("ATENCIÓN: Est?s a punto", "ATENCIÓN: Estás a punto"),
    ("Sistema restaurado con ?xito", "Sistema restaurado con éxito"),
    ("Archivo Excel generado con ?xito", "Archivo Excel generado con éxito"),
    ("Autom?tico", "Automático"),
    ("l?mite", "límite"),
    ("el d?a civil", "el día civil"),
    ("expl?c?to", "explícito"),
    ("?tiles", "útiles"),
    ("excepci?n de", "excepción de"),
    ("Acci?n</th>", "Acción</th>"),
    ("ATENCI?N: Est?s a punto", "ATENCIÓN: Estás a punto"),
    ("Recaudaci?n ? Costo", "Recaudación … Costo"),
    ("?Registrar? env?a automáticamente", "«Registrar» envía automáticamente"),
    ("Distribuci?n de servidores", "Distribución de servidores"),
    ("L?pez", "López"),
    ("Menú M?vil", "Menú Móvil"),
    ("M?dicas", "Médicas"),
    ("referencia de la Última copia autom?tica", "referencia de la Última copia automática"),
    ("registro(s) de copia autom?tica (restauración disponible)", "registro(s) de copia automática (restauración disponible)"),
    ("log(s) de copia autom?tica no se eliminan", "log(s) de copia automática no se eliminan"),
    ("Última copia autom?tica", "Última copia automática"),
    ("A?ade o elimina preguntas extra para este evento.", "Añade o elimina preguntas extra para este evento."),
    ("A?ade o elimina", "Añade o elimina"),
    ("autom?tica", "automática"),
    # --- Round 3: U+FFFD (archivo leído con codificación incorrecta) ---
    ("Opciones: \uFFFDEn qu\uFFFD \uFFFDrea les gustar\uFFFDa servir?", "Opciones: ¿En qué área les gustaría servir?"),
    ("Configuraci\uFFFDn de Precios", "Configuración de Precios"),
    ("Categor\uFFFDas de alergias", "Categorías de alergias"),
    ('title="A\uFFFDadir Sede"', 'title="Añadir Sede"'),
    ('placeholder="\uFFFDCu\uFFFDl?"', 'placeholder="¿Cuál?"'),
]
# Nota: no volver a ejecutar este script sobre un archivo ya en UTF-8 correcto (puede dañar texto).
# Tras correcciones: npm run check:utf8 && npm run build.
# Reparación puntual con U+FFFD disperso: scripts/repair_app_spanish_utf8.py

def main():
    path = TARGET
    # UTF-8 estricto: si falla, el archivo debe normalizarse antes (evita doble codificación).
    text = path.read_text(encoding="utf-8")
    original = text
    # Sort by key length descending
    reps = sorted(REPLACEMENTS, key=lambda x: len(x[0]), reverse=True)
    for old, new in reps:
        if old in text:
            text = text.replace(old, new)
    if text == original:
        print("No changes made", file=sys.stderr)
        return 1
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"Updated {path} ({len(original) - len(text) + sum(1 for a,b in zip(original, text) if a!=b)} chars changed approx)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
