import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appPath = path.join(__dirname, '..', 'src', 'App.jsx');

const BINDING_KEYS = [
  'MASKED_EXPENSE_CONCEPT_LABEL',
  'activeTab',
  'addLog',
  'allParticipants',
  'allergyOptionsForm',
  'allergyOptionsModal',
  'btnPrimary',
  'btnSecondary',
  'canAccessExpenses',
  'canSeeExpenseConceptForRow',
  'cashCutScheduleModal',
  'closePaymentMethodEditModal',
  'closeSuperDateEditModal',
  'currentEvent',
  'currentUser',
  'customFieldsModal',
  'data',
  'debugToast',
  'donationModal',
  'donations',
  'donationsListOpen',
  'editRegistryModal',
  'editorRegFieldsModalEl',
  'expenseEditModal',
  'expensePartialModal',
  'expenses',
  'fbUser',
  'formatMoney',
  'formatPhoneNumber',
  'getAutoPaymentService',
  'getDocRef',
  'globalConfig',
  'goBack',
  'goTo',
  'handleAddCustomField',
  'handleAddDonation',
  'handleAddLocation',
  'handleDeleteLocation',
  'handleEditExpense',
  'handleExpensePartialPayment',
  'handleExportExcel',
  'handleLogout',
  'handleRemoveCustomField',
  'handleSaveAllergyOptions',
  'handleSaveCashCutScheduleByLocation',
  'handleSavePaymentMethodEdit',
  'handleSavePricing',
  'handleSaveServeAreaOptions',
  'handleSuperSaveDateEdit',
  'handleUpdateEntry',
  'hasAdminRights',
  'hasFinancialAccess',
  'inputClasses',
  'inputClassesPhase',
  'isAddLocModalOpen',
  'isCampa',
  'isExporting',
  'isLocOpen',
  'isMobileMenuOpen',
  'isPanelNavSectionAllowed',
  'isSuperUser',
  'labelClasses',
  'labelClassesPhase',
  'locError',
  'mergeEventDonationsForEvent',
  'navHistory',
  'newCustomField',
  'newLocationName',
  'omitUndefinedDeep',
  'openDeleteDonationConfirm',
  'panelNavModalEl',
  'paymentMethodEditModal',
  'paymentModal',
  'pricingForm',
  'pricingModal',
  'publicQrBusy',
  'publicQrDataUrl',
  'publicQrModalOpen',
  'publicQrUrl',
  'renderBecadosPage',
  'renderCashCutPage',
  'renderEditRegistryModalFormFields',
  'renderExpenseListPage',
  'renderGlobalRegistryPage',
  'renderLocationSheet',
  'renderRegistryConfirmModal',
  'renderServerProfilesPage',
  'renderSummary',
  'resetEditRegistryModal',
  'selectedEventId',
  'sendWhatsAppMessage',
  'serveAreaOptionsForm',
  'serveAreaOptionsModal',
  'setAllergyOptionsForm',
  'setAllergyOptionsModal',
  'setCashCutScheduleModal',
  'setCashCutSlotTimeForLoc',
  'setCustomFieldsModal',
  'setDoc',
  'setDonationModal',
  'setDonationsListOpen',
  'setExpenseEditModal',
  'setExpensePartialModal',
  'setIsAddLocModalOpen',
  'setIsMobileMenuOpen',
  'setNewCustomField',
  'setNewLocationName',
  'setPaymentMethodEditModal',
  'setPaymentModal',
  'setPricingForm',
  'setPricingModal',
  'setPublicQrBusy',
  'setPublicQrDataUrl',
  'setPublicQrModalOpen',
  'setPublicQrOptional',
  'setPublicQrUrl',
  'setRenameModal',
  'setServeAreaOptionsForm',
  'setServeAreaOptionsModal',
  'setShowMoney',
  'setSuperDateEditModal',
  'setTempEventDate',
  'setWhatsAppModal',
  'showMoney',
  'showToast',
  'submitAbono',
  'summary',
  'superDateEditModal',
  'superSessionCount',
  'syncFirestoreBusy',
  'syncFirestoreFromServer',
  'systemView',
  'tempEventDate',
  'toggleCashCutServiceForLoc',
  'toggleDebugMode',
  'toast',
  'updateDoc',
  'visibleLocations',
  'whatsAppModal',
];

const objLines = ['  setAppShellBindings({', ...BINDING_KEYS.map((k) => `    ${k},`), '  });', '  return (', '    <Suspense fallback={<ScreenLoadingFallback title="Cargando evento…" />}>', '      <EventWorkspaceScreenLazy />', '    </Suspense>', '  );'];

let app = fs.readFileSync(appPath, 'utf8');

const startMarker = '  return (\n    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 flex overflow-hidden relative">';
const startIdx = app.indexOf(startMarker);
if (startIdx === -1) throw new Error('start marker not found');

const tailMarker = '\n};';
const exportIdx = app.indexOf('\nexport default App;');
if (exportIdx === -1) throw new Error('export default App not found');

const beforeExport = app.slice(0, exportIdx);
const closeFn = beforeExport.lastIndexOf(tailMarker);
if (closeFn === -1) throw new Error('closing }; before export not found');

const endReturn = beforeExport.lastIndexOf('  );', closeFn);
if (endReturn === -1) throw new Error('closing ); not found');

const newApp = app.slice(0, startIdx) + objLines.join('\n') + app.slice(endReturn + 4);
fs.writeFileSync(appPath, newApp, 'utf8');
console.log('patched App.jsx workspace return', { startIdx, endReturn });
