import fs from 'fs';

// Configuración de archivos (puedes cambiar los nombres aquí)
const inputFile = 'App.jsx';  // Pon aquí el nombre real de tu archivo (ej. 'App.js')
const outputFile = 'App_corregido.js'; // El archivo limpio que se generará

// Diccionario de reemplazos basado en los errores de tu código
// Nota: Utilizamos expresiones regulares (RegEx) para hacer el reemplazo exacto
const replacements = {
    // --- Signos de interrogación de apertura y frases comunes ---
    "\\?Est\\?s": "¿Estás",
    "\\?est\\?s": "¿estás",
    "\\?D\\?nde": "¿Dónde",
    "\\?d\\?nde": "¿dónde",
    "\\?En qu\\?": "¿En qué",
    "\\?Han servido": "¿Han servido",
    "\\?Sabe nadar\\?": "¿Sabe nadar?",
    "\\?Va con hijos\\?": "¿Va con hijos?",
    "\\?Es casado\\?": "¿Es casado?",
    "\\?Cu\\?l\\?": "¿Cuál?",
    "\\?cu\\?l\\?": "¿cuál?",
    "\\?Cu\\?ntos\\?": "¿Cuántos?",
    "\\?cu\\?ntos\\?": "¿cuántos?",
    "\\?Qu\\?": "¿Qué",
    "\\?qu\\?": "¿qué",
    "\\?C\\?mo": "¿Cómo",
    "\\?c\\?mo": "¿cómo",
    "\\?Cu\\?ndo": "¿Cuándo",
    "\\?cu\\?ndo": "¿cuándo",
    "\\?activa\\?": "¿activa?",
    "\\?Nos vemos": "¿Nos vemos",
    
    // --- Nombres propios y ciudades ---
    "P\\?rez": "Pérez",
    "p\\?rez": "pérez",
    "L\\?pez": "López",
    "l\\?pez": "lópez",
    "Quer\\?taro": "Querétaro",

    // --- Palabras con Ñ ---
    "A\\?adir": "Añadir",
    "a\\?adir": "añadir",
    "A\\?ade": "Añade",
    "a\\?ade": "añade",
    "A\\?adido": "Añadido",
    "a\\?adido": "añadido",
    "A\\?adi\\?": "Añadió",
    "a\\?adi\\?": "añadió",
    "pesta\\?a": "pestaña",
    "Pesta\\?a": "Pestaña",
    "pesta\\?as": "pestañas",
    "Pesta\\?as": "Pestañas",
    "Campa\\?a": "Campaña",
    "campa\\?a": "campaña",
    "Campa\\?as": "Campañas",
    "campa\\?as": "campañas",
    "contrase\\?a": "contraseña",
    "Contrase\\?a": "Contraseña",
    "contrase\\?as": "contraseñas",
    "Contrase\\?as": "Contraseñas",
    "Ni\\?os": "Niños",
    "ni\\?os": "niños",
    "Ni\\?o": "Niño",
    "ni\\?o": "niño",
    "Ni\\?a": "Niña",
    "ni\\?a": "niña",
    "dise\\?o": "diseño",
    "Dise\\?o": "Diseño",
    "tama\\?o": "tamaño",
    "Tama\\?o": "Tamaño",

    // --- Palabras específicas solicitadas y uso común ---
    "tel\\?fono": "teléfono",
    "Tel\\?fono": "Teléfono",
    "tel\\?fonos": "teléfonos",
    "Tel\\?fonos": "Teléfonos",
    "cortes\\?a": "cortesía",
    "Cortes\\?a": "Cortesía",
    "cortes\\?as": "cortesías",
    "Cortes\\?as": "Cortesías",
    "g\\?nero": "género",
    "G\\?nero": "Género",
    "G\\?NERO": "GÉNERO",

    // --- Palabras con acentos (á, é, í, ó, ú) ---
    "\\?rea\\b": "área",
    "\\?reas\\b": "áreas",
    "\\?ltimo": "último",
    "\\?ltima": "última",
    "\\?nico": "único",
    "\\?nica": "única",
    "\\?xito": "éxito",
    "J\\?venes": "Jóvenes",
    "j\\?venes": "jóvenes",
    "comisi\\?n": "comisión",
    "Comisi\\?n": "Comisión",
    "sesi\\?n": "sesión",
    "Sesi\\?n": "Sesión",
    "sesiones\\b": "sesiones",
    "opci\\?n": "opción",
    "Opci\\?n": "Opción",
    "P\\?gina": "Página",
    "p\\?gina": "página",
    "Adem\\?s": "Además",
    "est\\?": "está",
    "Est\\?": "Está",
    "est\\?n": "están",
    "Est\\?n": "Están",
    "Cami\\?n": "Camión",
    "cami\\?n": "camión",
    "Configuraci\\?n": "Configuración",
    "configuraci\\?n": "configuración",
    "Asignaci\\?n": "Asignación",
    "asignaci\\?n": "asignación",
    "donaci\\?n": "donación",
    "Donaci\\?n": "Donación",
    "donaciones\\b": "donaciones",
    "B\\?squeda": "Búsqueda",
    "b\\?squeda": "búsqueda",
    "Gesti\\?n": "Gestión",
    "gesti\\?n": "gestión",
    "Exportaci\\?n": "Exportación",
    "exportaci\\?n": "exportación",
    "Importaci\\?n": "Importación",
    "importaci\\?n": "importación",
    "depuraci\\?n": "depuración",
    "Depuraci\\?n": "Depuración",
    "antig\\?edad": "antigüedad",
    "Restauraci\\?n": "Restauración",
    "restauraci\\?n": "restauración",
    "Men\\?": "Menú",
    "men\\?": "menú",
    "m\\?nimo": "mínimo",
    "M\\?nimo": "Mínimo",
    "m\\?n\\.": "mín.",
    "M\\?n\\.": "Mín.",
    "m\\?s": "más",
    "inv\\?lido": "inválido",
    "inv\\?lida": "inválida",
    "M\\?TRICAS": "MÉTRICAS",
    "M\\?tricas": "Métricas",
    "m\\?tricas": "métricas",
    "M\\?todo": "Método",
    "m\\?todo": "método",
    "S\\?": "Sí",
    "s\\?": "sí",
    "evaluaci\\?n": "evaluación",
    "Evaluaci\\?n": "Evaluación",
    "cancelaci\\?n": "cancelación",
    "Cancelaci\\?n": "Cancelación",
    "devoluci\\?n": "devolución",
    "Devoluci\\?n": "Devolución",
    "recaudaci\\?n": "recaudación",
    "Recaudaci\\?n": "Recaudación",
    "edici\\?n": "edición",
    "Edici\\?n": "Edición",
    "Inscripci\\?n": "Inscripción",
    "inscripci\\?n": "inscripción",
    "informaci\\?n": "información",
    "Informaci\\?n": "Información",
    "acci\\?n": "acción",
    "Acci\\?n": "Acción",
    "categor\\?a": "categoría",
    "Categor\\?a": "Categoría",
    "autom\\?tica": "automática",
    "Autom\\?tico": "Automático",
    "autom\\?tico": "automático",
    "acu\\?ticas": "acuáticas",
    "Acu\\?ticas": "Acuáticas",
    "Din\\?mico": "Dinámico",
    "din\\?mico": "dinámico",
    "\\?tem": "ítem",
    "d\\?gitos": "dígitos",
    "D\\?gitos": "Dígitos",
    "d\\?a": "día",
    "D\\?a": "Día",
    "d\\?as": "días",
    "D\\?as": "Días",
    "gr\\?fica": "gráfica",
    "Gr\\?fica": "Gráfica",
    "gr\\?ficas": "gráficas",
    "Gr\\?ficas": "Gráficas",
    "auditor\\?a": "auditoría",
    "Auditor\\?a": "Auditoría",
    "secci\\?n": "sección",
    "Secci\\?n": "Sección",
    "promoci\\?n": "promoción",
    "Promoci\\?n": "Promoción",
    "aprobaci\\?n": "aprobación",
    "Aprobaci\\?n": "Aprobación",
    "vac\\?a": "vacía",
    "Vac\\?a": "Vacía",
    "a\\?n": "aún",
    "A\\?n": "Aún",
    "aqu\\?": "aquí",
    "Aqu\\?": "Aquí",
    "all\\?": "allí",
    "All\\?": "Allí",
    "ah\\?": "ahí",
    "Ah\\?": "Ahí",
    "Atr\\?s": "Atrás",
    "atr\\?s": "atrás",
    "M\\?dico": "Médico",
    "m\\?dico": "médico",
    "M\\?dicos": "Médicos",
    "m\\?dicos": "médicos",
    "M\\?dicas": "Médicas",
    "m\\?dicas": "médicas",
    "Espec\\?fico": "Específico",
    "espec\\?fico": "específico",
    "Espec\\?fica": "Específica",
    "espec\\?fica": "específica",
    "Gen\\?rico": "Genérico",
    "gen\\?rico": "genérico",
    "Pr\\?ximo": "Próximo",
    "pr\\?ximo": "próximo",
    "Num\\?rico": "Numérico",
    "num\\?rico": "numérico",
    "Expl\\?c\\?to": "Explícito",
    "expl\\?c\\?to": "explícito",
    "Sem\\?ntica": "Semántica",
    "sem\\?ntica": "semántica",
    "May\\?sculas": "Mayúsculas",
    "may\\?sculas": "mayúsculas",
    "Librer\\?a": "Librería",
    "librer\\?a": "librería",
    "Rengl\\?n": "Renglón",
    "rengl\\?n": "renglón",
    "Excepci\\?n": "Excepción",
    "excepci\\?n": "excepción",
    "Ambig\\?edad": "Ambigüedad",
    "ambig\\?edad": "ambigüedad",
    "Ning\\?n": "Ningún",
    "ning\\?n": "ningún",
    "Seg\\?n": "Según",
    "seg\\?n": "según",
    " t\\? ": " tú ",
    " T\\? ": " Tú ",
    " qu\\? ": " qué ",
    " Qu\\? ": " Qué ",
    " cu\\?ndo ": " cuándo ",
    " Cu\\?ndo ": " Cuándo ",
    " c\\?mo ": " cómo ",
    " C\\?mo ": " Cómo ",
    "mediod\\?a": "mediodía",
    "ser\\?": "será",
    "Ser\\?": "Será",

    // --- Verbos en pasado / participio (para los Logs y estados) ---
    "cambi\\?": "cambió",
    "activ\\?": "activó",
    "termin\\?": "terminó",
    "Sali\\?": "Salió",
    "sali\\?": "salió",
    "Abri\\?": "Abrió",
    "abri\\?": "abrió",
    "Cerr\\?": "Cerró",
    "cerr\\?": "cerró",
    "Cre\\?": "Creó",
    "cre\\?": "creó",
    "Renombr\\?": "Renombró",
    "renombr\\?": "renombró",
    "Actualiz\\?": "Actualizó",
    "actualiz\\?": "actualizó",
    "Elimin\\?": "Eliminó",
    "elimin\\?": "eliminó",
    "Revirti\\?": "Revirtió",
    "revirti\\?": "revirtió",
    "Restaur\\?": "Restauró",
    "restaur\\?": "restauró",
    "Inscribi\\?": "Inscribió",
    "inscribi\\?": "inscribió",
    "Archiv\\?": "Archivó",
    "archiv\\?": "archivó",
    "Reactiv\\?": "Reactivó",
    "reactiv\\?": "reactivó",
    "Promovi\\?": "Promovió",
    "promovi\\?": "promovió",
    "Registr\\?": "Registró",
    "registr\\?": "registró",
    "Agreg\\?": "Agregó",
    "agreg\\?": "agregó",
    "Baj\\?": "Bajó",
    "baj\\?": "bajó",
    "Subi\\?": "Subió",
    "subi\\?": "subió",
    "Escribi\\?": "Escribió",
    "escribi\\?": "escribió",
    "Recibi\\?": "Recibió",
    "recibi\\?": "recibió",
    "Acept\\?": "Aceptó",
    "acept\\?": "aceptó",
    "Rechaz\\?": "Rechazó",
    "rechaz\\?": "rechazó",
    "Aplic\\?": "Aplicó",
    "aplic\\?": "aplicó",
    "Quit\\?": "Quitó",
    "quit\\?": "quitó",
    "Descarg\\?": "Descargó",
    "descarg\\?": "descargó",
    "Gener\\?": "Generó",
    "gener\\?": "generó",
    "Marc\\?": "Marcó",
    "marc\\?": "marcó",
    "Envi\\?": "Envió",
    "envi\\?": "envió",
    "Abon\\?": "Abonó",
    "abon\\?": "abonó",
    "Pag\\?": "Pagó",
    "pag\\?": "pagó",
    "Liquid\\?": "Liquidó",
    "liquid\\?": "liquidó"
};

try {
    // 1. Leer el archivo dañado
    if (!fs.existsSync(inputFile)) {
        console.error(`❌ Error: No se encontró el archivo '${inputFile}'.`);
        console.error("Por favor, asegúrate de colocar el código dañado en el archivo correcto o ajusta el nombre en el script.");
        process.exit(1);
    }
    
    let content = fs.readFileSync(inputFile, 'utf8');

    // 2. Aplicar los reemplazos
    let totalReplacements = 0;
    
    for (const [corrupted, fixed] of Object.entries(replacements)) {
        // Expresión regular global ('g') para reemplazar todas las coincidencias
        const regex = new RegExp(corrupted, 'g');
        const matches = content.match(regex);
        
        if (matches) {
            totalReplacements += matches.length;
            content = content.replace(regex, fixed);
            console.log(`✅ Corregido: '${fixed}' (${matches.length} veces)`);
        }
    }

    // 3. Escribir el nuevo archivo
    fs.writeFileSync(outputFile, content, 'utf8');
    
    console.log("\n===============================================");
    console.log(`🎉 ¡Proceso terminado con éxito!`);
    console.log(`🔄 Se realizaron ${totalReplacements} correcciones en total.`);
    console.log(`💾 El código limpio ha sido guardado en: ${outputFile}`);
    console.log("===============================================\n");

} catch (error) {
    console.error("Ocurrió un error inesperado al procesar el archivo:", error);
}